import type { DiagramTemplate } from "./types";

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  {
    id: "basic-flowchart",
    name: "Basic Flowchart",
    description: "Simple start-to-end process flow",
    category: "flowchart",
    nodes: [
      {
        nodeType: "shape",
        positionX: 200,
        positionY: 50,
        width: 100,
        height: 50,
        data: {
          label: "Start",
          shapeType: "circle",
          color: "#22c55e",
          borderColor: "#16a34a",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 200,
        positionY: 150,
        width: 150,
        height: 60,
        data: {
          label: "Process 1",
          shapeType: "rectangle",
          color: "#3b82f6",
          borderColor: "#2563eb",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 200,
        positionY: 260,
        width: 100,
        height: 80,
        data: {
          label: "Decision?",
          shapeType: "diamond",
          color: "#f97316",
          borderColor: "#ea580c",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 200,
        positionY: 390,
        width: 150,
        height: 60,
        data: {
          label: "Process 2",
          shapeType: "rectangle",
          color: "#3b82f6",
          borderColor: "#2563eb",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 200,
        positionY: 500,
        width: 100,
        height: 50,
        data: {
          label: "End",
          shapeType: "circle",
          color: "#ef4444",
          borderColor: "#dc2626",
        },
        zIndex: 0,
      },
    ],
    edges: [
      {
        sourceNodeId: "0",
        targetNodeId: "1",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "1",
        targetNodeId: "2",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "3",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: { label: "Yes", targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "3",
        targetNodeId: "4",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
    ],
  },
  {
    id: "client-server",
    name: "Client-Server Architecture",
    description: "Basic client-server communication diagram",
    category: "network",
    nodes: [
      {
        nodeType: "icon",
        positionX: 100,
        positionY: 150,
        width: 80,
        height: 80,
        data: {
          label: "Client",
          icon: "Monitor",
          color: "#3b82f6",
          borderColor: "#2563eb",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 300,
        positionY: 150,
        width: 80,
        height: 80,
        data: {
          label: "Load Balancer",
          icon: "Network",
          color: "#8b5cf6",
          borderColor: "#7c3aed",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 500,
        positionY: 50,
        width: 80,
        height: 80,
        data: {
          label: "Server 1",
          icon: "Server",
          color: "#22c55e",
          borderColor: "#16a34a",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 500,
        positionY: 250,
        width: 80,
        height: 80,
        data: {
          label: "Server 2",
          icon: "Server",
          color: "#22c55e",
          borderColor: "#16a34a",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 700,
        positionY: 150,
        width: 80,
        height: 80,
        data: {
          label: "Database",
          icon: "Database",
          color: "#f97316",
          borderColor: "#ea580c",
        },
        zIndex: 0,
      },
    ],
    edges: [
      {
        sourceNodeId: "0",
        targetNodeId: "1",
        edgeType: "smoothstep",
        data: { label: "Request", targetArrow: "arrowclosed", sourceArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "1",
        targetNodeId: "2",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "1",
        targetNodeId: "3",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "4",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed", sourceArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "3",
        targetNodeId: "4",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed", sourceArrow: "arrowclosed" },
      },
    ],
  },
  {
    id: "org-chart",
    name: "Organization Chart",
    description: "Simple organizational hierarchy",
    category: "org-chart",
    nodes: [
      {
        nodeType: "shape",
        positionX: 300,
        positionY: 50,
        width: 150,
        height: 60,
        data: {
          label: "CEO",
          shapeType: "rectangle",
          color: "#8b5cf6",
          borderColor: "#7c3aed",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 100,
        positionY: 180,
        width: 140,
        height: 60,
        data: {
          label: "CTO",
          shapeType: "rectangle",
          color: "#3b82f6",
          borderColor: "#2563eb",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 300,
        positionY: 180,
        width: 140,
        height: 60,
        data: {
          label: "CFO",
          shapeType: "rectangle",
          color: "#22c55e",
          borderColor: "#16a34a",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 500,
        positionY: 180,
        width: 140,
        height: 60,
        data: {
          label: "COO",
          shapeType: "rectangle",
          color: "#f97316",
          borderColor: "#ea580c",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 50,
        positionY: 310,
        width: 120,
        height: 50,
        data: {
          label: "Engineering",
          shapeType: "rectangle",
          color: "#64748b",
          borderColor: "#475569",
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 200,
        positionY: 310,
        width: 120,
        height: 50,
        data: {
          label: "Product",
          shapeType: "rectangle",
          color: "#64748b",
          borderColor: "#475569",
        },
        zIndex: 0,
      },
    ],
    edges: [
      {
        sourceNodeId: "0",
        targetNodeId: "1",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: {},
      },
      {
        sourceNodeId: "0",
        targetNodeId: "2",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: {},
      },
      {
        sourceNodeId: "0",
        targetNodeId: "3",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: {},
      },
      {
        sourceNodeId: "1",
        targetNodeId: "4",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: {},
      },
      {
        sourceNodeId: "1",
        targetNodeId: "5",
        sourceHandle: "bottom-source",
        targetHandle: "top",
        edgeType: "smoothstep",
        data: {},
      },
    ],
  },
  {
    id: "user-flow",
    name: "User Flow",
    description: "User journey through application screens",
    category: "flowchart",
    nodes: [
      {
        nodeType: "shape",
        positionX: 100,
        positionY: 100,
        width: 140,
        height: 80,
        data: {
          label: "Landing Page",
          shapeType: "rectangle",
          color: "#3b82f6",
          borderColor: "#2563eb",
          borderRadius: 12,
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 300,
        positionY: 100,
        width: 140,
        height: 80,
        data: {
          label: "Sign Up",
          shapeType: "rectangle",
          color: "#22c55e",
          borderColor: "#16a34a",
          borderRadius: 12,
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 500,
        positionY: 100,
        width: 140,
        height: 80,
        data: {
          label: "Dashboard",
          shapeType: "rectangle",
          color: "#8b5cf6",
          borderColor: "#7c3aed",
          borderRadius: 12,
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 400,
        positionY: 250,
        width: 140,
        height: 80,
        data: {
          label: "Settings",
          shapeType: "rectangle",
          color: "#64748b",
          borderColor: "#475569",
          borderRadius: 12,
        },
        zIndex: 0,
      },
      {
        nodeType: "shape",
        positionX: 600,
        positionY: 250,
        width: 140,
        height: 80,
        data: {
          label: "Profile",
          shapeType: "rectangle",
          color: "#ec4899",
          borderColor: "#db2777",
          borderRadius: 12,
        },
        zIndex: 0,
      },
    ],
    edges: [
      {
        sourceNodeId: "0",
        targetNodeId: "1",
        edgeType: "smoothstep",
        data: { label: "Sign Up", targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "1",
        targetNodeId: "2",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "3",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "4",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
    ],
  },
  {
    id: "microservices",
    name: "Microservices Architecture",
    description: "Microservices with API gateway pattern",
    category: "network",
    nodes: [
      {
        nodeType: "icon",
        positionX: 100,
        positionY: 200,
        width: 80,
        height: 80,
        data: {
          label: "Mobile App",
          icon: "Smartphone",
          color: "#3b82f6",
          borderColor: "#2563eb",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 100,
        positionY: 80,
        width: 80,
        height: 80,
        data: {
          label: "Web App",
          icon: "Monitor",
          color: "#3b82f6",
          borderColor: "#2563eb",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 280,
        positionY: 140,
        width: 80,
        height: 80,
        data: {
          label: "API Gateway",
          icon: "Network",
          color: "#8b5cf6",
          borderColor: "#7c3aed",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 460,
        positionY: 50,
        width: 80,
        height: 80,
        data: {
          label: "Auth Service",
          icon: "Shield",
          color: "#ef4444",
          borderColor: "#dc2626",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 460,
        positionY: 170,
        width: 80,
        height: 80,
        data: {
          label: "User Service",
          icon: "Users",
          color: "#22c55e",
          borderColor: "#16a34a",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 460,
        positionY: 290,
        width: 80,
        height: 80,
        data: {
          label: "Order Service",
          icon: "FileText",
          color: "#f97316",
          borderColor: "#ea580c",
        },
        zIndex: 0,
      },
      {
        nodeType: "icon",
        positionX: 640,
        positionY: 170,
        width: 80,
        height: 80,
        data: {
          label: "Database",
          icon: "Database",
          color: "#64748b",
          borderColor: "#475569",
        },
        zIndex: 0,
      },
    ],
    edges: [
      {
        sourceNodeId: "0",
        targetNodeId: "2",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "1",
        targetNodeId: "2",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "3",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "4",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "2",
        targetNodeId: "5",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "4",
        targetNodeId: "6",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed", sourceArrow: "arrowclosed" },
      },
      {
        sourceNodeId: "5",
        targetNodeId: "6",
        edgeType: "smoothstep",
        data: { targetArrow: "arrowclosed", sourceArrow: "arrowclosed" },
      },
    ],
  },
];

// Group templates by category
export function getTemplatesByCategory(): Map<string, DiagramTemplate[]> {
  const byCategory = new Map<string, DiagramTemplate[]>();
  DIAGRAM_TEMPLATES.forEach((template) => {
    const existing = byCategory.get(template.category) || [];
    existing.push(template);
    byCategory.set(template.category, existing);
  });
  return byCategory;
}

// Category display names
export const TEMPLATE_CATEGORY_NAMES: Record<string, string> = {
  flowchart: "Flowcharts",
  network: "Network & Architecture",
  "org-chart": "Organization Charts",
  sequence: "Sequence Diagrams",
  general: "General",
};
